apiVersion: v1
kind: Service
metadata:
  name: server-outside
  labels:
    app: server
spec:
  ports:
  - port: 1884
    protocol: TCP
    targetPort: 1883
  selector:
    app: server
  type: NodePort
